services:
  postgres-db:
    image: postgres:14
    container_name: authvault_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: no

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: ${ACTIVEMQ_USER}
      ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVEMQ_PASSWORD}
    ports:
      - "${ACTIVEMQ_PORT}:${ACTIVEMQ_PORT}"
      - "${ACTIVEMQ_WEB_PORT}:${ACTIVEMQ_WEB_PORT}"
    volumes:
      - activemq-data:/var/activemq/data
    restart: always

  authvault-app:
    build: .
    image: authvault_app:latest
    container_name: authvault_app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres-db
      - activemq
    restart: no

volumes:
  postgres-data:
  activemq-data:
