services:
  postgres-db:
    image: postgres:14
    container_name: authvault_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: no

  authvault-app:
    build: .
    image: authvault_app:latest
    container_name: authvault_app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres-db
    restart: no

volumes:
  postgres-data:
